### ISSUE TITLE
asmewide.sty has old version of cuted.sty

### ISSUE THREAD

**Issue by trssssrt** [John02139/asmeconf#4]
**Describe the bug**
When compiling _asmeconf-template-widetext.tex_ multiple errors are produced that all originate from _asmewide.sty_ (see screenshot for errors).

 **Steps To Reproduce Error**

1. Go to CTAN [asmeconf page](https://ctan.org/pkg/asmeconf)
2. Download [latest version](https://mirrors.ctan.org/macros/latex/contrib/asmeconf.zip)
3. Import downloaded ZIP into Overleaf as a new project
4. Compile _asmeconf-template-widetext.tex_

**Screenshots**
![image](https://user-images.githubusercontent.com/34108479/174150276-51d6f793-d1e0-4e99-b212-9823b7a6a51a.png)

**Platform (please complete the following information):**
 - OS: Windows Version 21H1 (OS Build 19043.1706)
 - asmeconf Version: 1.30 2022-03-14
 - Tex Package: Overleaf
 - Browser: Chrome, Brave, and Microsoft Edge

**Comment by John02139** [comment]
The first error message is generated by asmewide.sty, but not caused by it.  Asmewide is telling you that the version of cuted.sty you are using is too old to support the asmewide.sty package.  You must have cuted.sty v2.0 or later to run asmewide.sty.   Presumably, Overleaf does not have the most recent version of cuted.sty in its installation.

The remaining error messages are the result of having an old version of cuted.sty that does not define the command \preCutedStrip{...}. 

The best solution would be for Overleaf to update its installation, but they are generally not as current as CTAN.

Instead, you can obtain cuted.sty v2.0 or higher and put that file into your working directory.  cuted.sty calls flushend.sty v4.0 or higher.  Both of these packages are in the sttools bundle on ctan.org. 

The process is as follows:

1. Go to CTAN and download the sttools bundle, here: https://ctan.org/pkg/sttools   
2. The entire bundle can be downloaded as a zip archive from that page.
3. Unzip the bundle (maybe do this in separate directory for convenience)
4. Run "tex sttools.ins".  This will generate the needed sty files in that directory.
5. Move cuted.sty and flushend.sty to the working directory of your asme paper.
6. Try latexing your paper again, hopefully now without errors.

**Comment by John02139** [comment]
PS: Thanks for this report.

**Comment by trssssrt** [comment]
My mistake, I misread the error. 
Follow up: Overleaf will be updating cuted.sty (and other styles) at the end of the third quarter 2022. For anyone else who encounters this problem, you can use the most recent package versions by downloading the package's .sty file from a TeX live development source and uploading it to your project: [https://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/sttools/](https://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/sttools/)
