### ISSUE TITLE
Texmaker Compilation Error

### ISSUE THREAD

**Issue by Vom1124** [John02139/asmeconf#9]
**Describe the bug**
!Undefined control sequence \DocumentMetadata{

**Screenshots**
! Undefined control sequence.
l.154 \tag_if_active:T
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
\BKM@id=\count315
))
(C:\Users\vomsh\AppData\Local\Programs\MiKTeX\tex/latex/hyperxmp\hyperxmp.sty
Package: hyperxmp 2023/09/10 v5.12 Store hyperref metadata in XMP format
! Undefined control sequence.
l.26 \IfDocumentMetadataTF
{%
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
Package hyperxmp Warning: Disabling hyperxmp because it is incompatible with PD
F management on input line 29.

**Platform (please complete the following information):**
 - OS: [wINDOWS 11]
 - TeX Program [e.g. Texmaker 5.1.4]

**Comment by John02139** [comment]
You maybe running an old version of Latex that does not support the \DocumentMetadata function, or possibly an old version of asmeconf.

Quick solution:  delete or comment out  \DocumentMetadata{.... } from your file.

But check that you are running the most current version of asmeconf (v1.37) and that your Latex installation is up-to-date.

**Comment by Vom1124** [comment]
Hello John,I have updated the Texmaker to the latest available right now, which is 5.1.4. I tried inversions 5.0.4 and 5.1.4. Both of which yielded the same error. I have tried in commenting the \DocumentMetadata line, it still results in an error from \IfDocumentMetadata and \begin{document} lines. Sent from my iPhoneOn May 15, 2024, at 21:21, John ***@***.***> wrote:﻿
You are running an old version of Latex that does not support the \DocumentMetadata function.
Quick solution:  delete or comment out  \DocumentMetadata{.... } from your file.
Lasting solution:  update your installation to the current version of Latex.

**Comment by John02139** [comment]
The issue may not be the front-end program "texmaker" per se. The issue is the version of the latex kernel and associated latex packages that you have. One of them does not include the definition of "\IfDocumentMetadataTF"

"\IfDocumentMetadata" is not defined in asmeconf, but it is used in hyperxmp which gets loaded if you do not have a current source that defines \DocumentMetadata AND if you use the option "pdf-a".

**Try removing the "pdf-a" option from your \documentclass[..] options.  That should prevent calling hyperxmp.**

With a current version of Latex (e.g., Tex Live 2023) the problem does not occur.

**Comment by Vom1124** [comment]
I am currently using MikTex as my latex distribution.

I commented/removed the \DocumentMeta and also the pdf-a from the document
class line. But now the problem still persists on the
"\IfDocumentMetadataTF".

I am having troubles updating MikTex as well, I am on it though.

**Comment by Vom1124** [comment]
Hello Dr. John,

After re-installing the MikTex and Texmaker, and then running the updates
fixed the issue. But before updating the MikTex, just removing the pd-a and
commenting \DocumentMetadata yielded the same consistent errors. I am
guessing that in the actual asmeconf.cls file, there are instance of "if"
conditions that still calls out pdfManagement (or looks for
\DocumentMetadata) parameters.

I really appreciate your prompt response. I had a paper due last night, I
couldn't figure out this issue, and thus, ended up using the asm2e class
file instead by making necessary modifications.

Vom

**Comment by John02139** [comment]
Thanks for your note, Vom.  Yes, asmeconf loads hyperxmp for the management of pdf metadata when `\DocumentMetadata` is not called (even without the pdf-a option).  (It was very late my time when you wrote, and I overlooked that.)  However, the problem was outside asmeconf and was fixed when you updated your installation.

To clarify the issue for anyone else reading this thread, let me add some TeXnical details.

The log messages showed that three commands were undefined. 

`\DocumentMetadata`
`\IfDocumentMetadataTF`
`\tag_if_active:T`

The first and second commands are defined by the Latex kernel in versions June 2022 and later. For details, see:

[source2e.pdf](https://ctan.math.illinois.edu/macros/latex/base/source2e.pdf ) (file p: ltmeta.dtx)
[ltnews35.pdf](https://www.latex-project.org/news/latex2e-news/ltnews35.pdf )

The third command, `\tag_if_active:T`, is defined by Latex if the `\DocumentMetadata` command is called. 

Recent versions of the hyperxmp package call `\IfDocumentMetadataTF`.   (hyperxmp does not check whether the command is def'd before using it.)  So there was apparently also mismatch between the Latex version and the hyperxmp version in the OP's installation. 

Updating the installation resolved all three issues for the OP.  Nothing needed to be changed in asmeconf.
